name: gh-printer
description: Outputs the results of the actions to the specified file.
author: ROBOT

branding:
  icon: printer
  color: blue

inputs:
  output-file:
    description: gh-printer's output file
  contents:
    description: printer contents

outputs:
  output-file:
    description: gh-printer's output file

runs:
  using: node20
  main: dist/index.js
