name: gh-printer
description: Outputs the results of the actions to the specified file.
author: ROBOT

branding:
  icon: printer
  color: blue

inputs:
  github-token:
    description: gh-printer's github token
    required: true
  output-file:
    description: gh-printer's output file
    required: true
  input-file:
    description: gh-printer's input file
    required: false
  contents:
    description: printer contents
    required: false
  run:
    description: run commands
    required: false
  ignore-input-file:
    description: ignore gh-printer's input-file
    default: true
    required: false

outputs:
  output-file:
    description: gh-printer's output file

runs:
  using: node20
  main: dist/index.js
