name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - v*
  push:
    branches:
      - main
      - v*

jobs:
  test-typescript:
    name: TypeScript Tests

    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-unixtime:
    name: Generate Update Log
    runs-on: ubuntu-latest

    env:
      unixtime: 0

    steps:
      - name: Get Unixtime
        id: get-unixtime
        run: echo "unixtime=$(date +%s)" >> $GITHUB_ENV

    outputs:
      unixtime: ${{ env.unixtime }}

  test-action:
    name: GitHub Actions Test

    permissions:
      pull-requests: write
      contents: write

    runs-on: ubuntu-latest
    needs: test-unixtime

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: ./tests/last-update.txt
          contents: ${{ needs.test-unixtime.outputs.unixtime }}

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"
