name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - v*

jobs:
  test-typescript:
    name: TypeScript Tests

    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-unixtime:
    name: Generate Update Log
    runs-on: ubuntu-latest

    outputs:
      unixtime: ${{ steps.get-unixtime.outputs.unixtime }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Get Unixtime
        id: get-unixtime
        run: echo "unixtime=$(date +%s)" >> "$GITHUB_OUTPUT"

      - name: Generate Message
        id: generate-msg
        run: echo "$(npm run actions)" > test.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test
          path: test.txt

  test-action-contents:
    name: GitHub Actions Test

    permissions:
      pull-requests: write
      contents: write

    runs-on: ubuntu-latest
    needs: test-unixtime

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: ./tests/last-update.txt
          contents: "Updated at ${{ needs.test-unixtime.outputs.unixtime }}."

  test-action-file:
    name: GitHub Actions Test

    permissions:
      pull-requests: write
      contents: write

    runs-on: ubuntu-latest
    needs: test-unixtime

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: test

      - name: Test Local Action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: ./tests/log.txt
          input-file: ./test.txt

  test-action-run:
    name: GitHub Actions Test

    permissions:
      pull-requests: write
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Test Local Action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: ./tests/run.txt
          run: npm run test
