name: Update Main Version
run-name: Move ${{ github.event.inputs.major_version }} to ${{ github.event.inputs.target }}

on:
  workflow_dispatch:
    inputs:
      target:
        description: The tag or reference to use
        required: true
      major_version:
        type: choice
        description: The major version to update
        options:
          - v4
          - v3
          - v2
          - v1

jobs:
  tag:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0
      - name: Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Tag new target
        run: git tag -f ${{ github.event.inputs.major_version }} ${{ github.event.inputs.target }}
      - name: Push new tag
        run: git push origin ${{ github.event.inputs.major_version }} --force
